### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kekepr1** [Jp-17/Coding_learning#1]

**Comment by Jp-17** [comment]
哈哈哈是的，你是？

**Comment by kekepr1** [comment]
学长好！我叫刘博宇。您现在是贾晓轩贾老师的实验室的成员吗？我想请问一下贾老师现在是不是还在招收科研助理。受公司的清华前辈推荐，我拜读了贾老师发表的一些paper，对贾老师实验室所进行的认知科学、脑机接口领域研究非常感兴趣！

我非常想做贾老师实验室的科研助理，但我的履历并不算特别优秀（扬州大学生物技术专业学士），只投简历可能会被直接刷下。所以我打算在投简历时，顺带写一下对贾老师paper的一些小见解或者疑问，并且附带我在生物公司时写的科普文章示例（包含对SCI等期刊论文的临床试验解读）。但毕竟时间精力有限，中枢神经系统相关实验的专有术语也很多，导致进展不快。距离贾老师发布招聘信息已经快一个月了，不知道贾老师这边的招收情况如何，非常着急。所以先找到您，想要了解一下情况。万分感谢！
（以及，您的名字是哪两个字呢？我在国内外网络找了挺久不知道该怎么称呼您，只能以JiangPeng学长代称了...）

**Comment by Jp-17** [comment]
哈哈哈原来如此。你好呀，我叫蒋鹏，现在是贾老师实验室博一（即将博二）的学生。贾老师确实在招收科研助理，但是应该已经招到了一个同学即将入职。另外，除了传统的神经科学知识，我们实验室这边对计算也有一定要求（比如利用python进行数据分析等）。这是我这边提供的简单情况~

**Comment by Jp-17** [comment]
但我们还挺缺人的，你也可以继续联系贾老师试试，祝你好运~

**Comment by kekepr1** [comment]
啊好的，多谢蒋学长！可是我看到招聘界面也有一个科研助理（实验方向）的信息呀：
![image](https://user-images.githubusercontent.com/63789564/175809544-ef65c27f-9d0f-49e3-852a-ebf2725703a4.png)
这个（2.）也需要使用python的能力嘛？

**Comment by kekepr1** [comment]
> 但我们还挺缺人的，你也可以继续联系贾老师试试，祝你好运~

非常感谢！我现在也很希望能有这个锻炼实验技术和思维的机会，估计几天后我再投给贾老师的邮箱去。

**Comment by Jp-17** [comment]
> 

有计算背景是绝对的加分项，总之可以试试，加油~

**Comment by kekepr1** [comment]
> > 
> 
> 有计算背景是绝对的加分项，总之可以试试，加油~

好的，多谢学长解答，打扰了~

**Comment by kekepr1** [comment]
蒋学长晚上好！前几天我把简历和自荐信发到贾老师邮箱了，不过一直没有消息。我知道这可能意味着落选了，但毕竟Gmail邮箱（jxiaoxuan@gmail.com）在国内容易漏收，能麻烦您帮我问一问贾老师是否有收到嘛？当然如果确认遗憾落选的话，我就放下心另谋出路啦~ @Jp-17
